volumes:
  totp-data:

services:
  totp-web:
    image: suterdev/totp:latest
    restart: always
    ports:
      - 5000:5000
    volumes:
      - totp-data:/var/www/html/data
    environment:
      - APP_KEY=SOMERANDOMKEYGOESHERE
      - APP_NAME=TOTP
      - APP_DEBUG=0
